<?php

declare(strict_types=1);

namespace App\Command;

use App\Entity\Vendor;
use App\Service\DclApiService;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Yaml\Yaml;

/**
 * Sync vendor and product data from the Matter Distributed Compliance Ledger (DCL) to YAML fixtures.
 */
#[AsCommand(
    name: 'app:dcl:sync',
    description: 'Fetch vendor and product data from Matter DCL API and generate YAML fixtures',
)]
class DclSyncCommand extends Command
{
    private const DEFAULT_OUTPUT_DIR = 'fixtures';

    public function __construct(
        private readonly DclApiService $dclApiService,
        private readonly string $projectDir,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('vendors-only', null, InputOption::VALUE_NONE, 'Only sync vendors')
            ->addOption('products-only', null, InputOption::VALUE_NONE, 'Only sync products')
            ->addOption('output-dir', 'o', InputOption::VALUE_REQUIRED, 'Output directory for YAML files', self::DEFAULT_OUTPUT_DIR);
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $outputDir = $this->projectDir . '/' . $input->getOption('output-dir');

        $vendorsOnly = $input->getOption('vendors-only');
        $productsOnly = $input->getOption('products-only');

        if (!is_dir($outputDir)) {
            $io->error(\sprintf('Output directory does not exist: %s', $outputDir));

            return Command::FAILURE;
        }

        $io->title('Matter DCL Data Sync');

        // Sync vendors
        if (!$productsOnly) {
            $this->syncVendors($io, $outputDir);
        }

        // Sync products
        if (!$vendorsOnly) {
            $this->syncProducts($io, $outputDir);
        }

        $io->success('DCL sync complete!');

        return Command::SUCCESS;
    }

    private function syncVendors(SymfonyStyle $io, string $outputDir): void
    {
        $io->section('Fetching vendors from DCL API...');

        $vendors = $this->dclApiService->fetchAllVendors();
        $io->info(\sprintf('Fetched %d vendors', \count($vendors)));

        // Transform to fixture format
        $fixtures = [];
        foreach ($vendors as $vendor) {
            $name = $vendor['vendorName'] ?? '';
            $specId = $vendor['vendorID'] ?? 0;

            // Generate unique slug with specId suffix (e.g., 'govee-4947')
            $baseSlug = Vendor::generateSlug($name, $specId);
            $slug = $baseSlug . '-' . $specId;

            $fixtures[] = [
                'specId' => $specId,
                'name' => $name,
                'slug' => $slug,
                'companyLegalName' => $vendor['companyLegalName'] ?? null,
                'vendorLandingPageURL' => $vendor['vendorLandingPageURL'] ?? null,
            ];
        }

        // Sort by specId for consistent output
        usort($fixtures, fn ($a, $b) => $a['specId'] <=> $b['specId']);

        // Write YAML file
        $yamlContent = "# Matter Vendors from DCL (Distributed Compliance Ledger)\n";
        $yamlContent .= "# Auto-generated by app:dcl:sync - do not edit manually\n";
        $yamlContent .= "# Source: https://on.dcl.csa-iot.org/dcl/vendorinfo/vendors\n";
        $yamlContent .= "# Generated: " . date('Y-m-d H:i:s') . "\n\n";
        $yamlContent .= Yaml::dump($fixtures, 2, 2);

        $vendorsFile = $outputDir . '/vendors.yaml';
        file_put_contents($vendorsFile, $yamlContent);

        $io->success(\sprintf('Wrote %d vendors to %s', \count($fixtures), $vendorsFile));
    }

    private function syncProducts(SymfonyStyle $io, string $outputDir): void
    {
        $io->section('Fetching products from DCL API...');

        $models = $this->dclApiService->fetchAllModels();
        $io->info(\sprintf('Fetched %d products', \count($models)));

        // Transform to fixture format
        $fixtures = [];
        foreach ($models as $model) {
            $fixture = [
                'vendorId' => $model['vid'] ?? 0,
                'productId' => $model['pid'] ?? 0,
                'productName' => $model['productName'] ?? null,
                'productLabel' => $model['productLabel'] ?? null,
                'deviceTypeId' => $model['deviceTypeId'] ?? null,
                'partNumber' => $model['partNumber'] ?? null,
            ];

            // Only include non-empty URLs
            if (!empty($model['productUrl'])) {
                $fixture['productUrl'] = $model['productUrl'];
            }
            if (!empty($model['supportUrl'])) {
                $fixture['supportUrl'] = $model['supportUrl'];
            }
            if (!empty($model['userManualUrl'])) {
                $fixture['userManualUrl'] = $model['userManualUrl'];
            }
            if (!empty($model['commissioningCustomFlowUrl'])) {
                $fixture['commissioningCustomFlowUrl'] = $model['commissioningCustomFlowUrl'];
            }
            if (!empty($model['maintenanceUrl'])) {
                $fixture['maintenanceUrl'] = $model['maintenanceUrl'];
            }

            // Commissioning and discovery fields (only include if set)
            if (isset($model['discoveryCapabilitiesBitmask'])) {
                $fixture['discoveryCapabilitiesBitmask'] = $model['discoveryCapabilitiesBitmask'];
            }
            if (isset($model['commissioningCustomFlow'])) {
                $fixture['commissioningCustomFlow'] = $model['commissioningCustomFlow'];
            }
            if (isset($model['commissioningModeInitialStepsHint'])) {
                $fixture['commissioningModeInitialStepsHint'] = $model['commissioningModeInitialStepsHint'];
            }
            if (!empty($model['commissioningModeInitialStepsInstruction'])) {
                $fixture['commissioningModeInitialStepsInstruction'] = $model['commissioningModeInitialStepsInstruction'];
            }

            // Factory reset fields
            if (isset($model['factoryResetStepsHint'])) {
                $fixture['factoryResetStepsHint'] = $model['factoryResetStepsHint'];
            }
            if (!empty($model['factoryResetStepsInstruction'])) {
                $fixture['factoryResetStepsInstruction'] = $model['factoryResetStepsInstruction'];
            }

            $fixtures[] = $fixture;
        }

        // Sort by vendorId, then productId for consistent output
        usort($fixtures, function ($a, $b) {
            if ($a['vendorId'] !== $b['vendorId']) {
                return $a['vendorId'] <=> $b['vendorId'];
            }

            return $a['productId'] <=> $b['productId'];
        });

        // Write YAML file
        $yamlContent = "# Matter Products from DCL (Distributed Compliance Ledger)\n";
        $yamlContent .= "# Auto-generated by app:dcl:sync - do not edit manually\n";
        $yamlContent .= "# Source: https://on.dcl.csa-iot.org/dcl/model/models\n";
        $yamlContent .= "# Generated: " . date('Y-m-d H:i:s') . "\n\n";
        $yamlContent .= Yaml::dump($fixtures, 2, 2);

        $productsFile = $outputDir . '/products.yaml';
        file_put_contents($productsFile, $yamlContent);

        $io->success(\sprintf('Wrote %d products to %s', \count($fixtures), $productsFile));
    }
}
