<?php

declare(strict_types=1);

namespace App\Command;

use App\Service\ZclParser;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Yaml\Yaml;

/**
 * Snapshot the Matter cluster spec at each released spec version.
 *
 * Unlike app:zap:sync (which updates the annotated fixtures/clusters.yaml against
 * a single ref, preserving hand-curated descriptions/categories), this command
 * dumps a fresh per-version snapshot of upstream-derived data only. It writes
 * one fixtures/clusters/{version}.yaml per Matter release in MATTER_VERSIONS.
 *
 * Run once after a parser change or when CSA cuts a new spec release. Each
 * historical file is otherwise frozen — git tags upstream don't move, so
 * re-running against the same tag is a no-op modulo timestamp drift.
 */
#[AsCommand(
    name: 'app:zap:backfill',
    description: 'Snapshot Matter cluster spec into per-version fixture files (fixtures/clusters/{1.0..1.5}.yaml)',
)]
final class ZapBackfillCommand extends Command
{
    /**
     * High-level Matter spec version → connectedhomeip git tag. Each tag is the
     * latest patch release in its line (CSA late patches occasionally adjust
     * conformance or bump a ClusterRevision; the patch tag is what certified
     * devices were tested against).
     */
    private const array MATTER_VERSIONS = [
        '1.0' => 'v1.0.0.2',
        '1.1' => 'v1.1.0.2',
        '1.2' => 'v1.2.0.1',
        '1.3' => 'v1.3.0.0',
        '1.4' => 'v1.4.2.0',
        '1.5' => 'v1.5.1.0',
    ];

    private const string DEFAULT_OUTPUT_DIR = 'fixtures/clusters';

    public function __construct(
        private readonly ZclParser $parser,
        private readonly string $projectDir,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('matter-version', null, InputOption::VALUE_REQUIRED, 'Backfill only the named Matter version (e.g. "1.4")')
            ->addOption('output-dir', 'o', InputOption::VALUE_REQUIRED, 'Output directory for per-version YAML files', self::DEFAULT_OUTPUT_DIR);
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $outputDir = $this->projectDir.'/'.$input->getOption('output-dir');
        $only = $input->getOption('matter-version');

        $io->title('Matter Cluster Spec Backfill');

        if (!is_dir($outputDir) && !mkdir($outputDir, 0755, true) && !is_dir($outputDir)) {
            $io->error(\sprintf('Could not create output directory: %s', $outputDir));

            return Command::FAILURE;
        }

        $versions = self::MATTER_VERSIONS;
        if (null !== $only) {
            if (!isset($versions[$only])) {
                $io->error(\sprintf('Unknown Matter version "%s". Known: %s', $only, implode(', ', array_keys(self::MATTER_VERSIONS))));

                return Command::FAILURE;
            }
            $versions = [$only => $versions[$only]];
        }

        foreach ($versions as $version => $ref) {
            $outputFile = \sprintf('%s/%s.yaml', $outputDir, $version);
            $io->section(\sprintf('Matter %s (ref %s) → %s', $version, $ref, $outputFile));

            try {
                $files = $this->parser->fetchClusterFileList($ref);
            } catch (\Throwable $e) {
                $io->error(\sprintf('Failed to fetch zcl.json for %s: %s', $ref, $e->getMessage()));

                return Command::FAILURE;
            }

            if ([] === $files) {
                $io->warning(\sprintf('No cluster files listed at ref %s — skipping', $ref));
                continue;
            }

            $io->progressStart(\count($files));
            $clusters = [];
            foreach ($files as $file) {
                foreach ($this->parser->fetchAndParseClusterXml($file, $ref) as $cluster) {
                    $clusters[] = $cluster;
                }
                $io->progressAdvance();
            }
            $io->progressFinish();

            usort($clusters, fn (array $a, array $b): int => $a['id'] <=> $b['id']);

            $yamlContent = "# Matter Cluster Definitions — Matter {$version} snapshot\n";
            $yamlContent .= "# Generated by app:zap:backfill from connectedhomeip ZAP XML\n";
            $yamlContent .= \sprintf("# Source ref: %s\n", $ref);
            $yamlContent .= '# Snapshot date: '.date('Y-m-d H:i:s')."\n\n";
            $yamlContent .= Yaml::dump($clusters, 6, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);

            file_put_contents($outputFile, $yamlContent);
            $io->info(\sprintf('Wrote %d clusters to %s', \count($clusters), $outputFile));
        }

        $io->newLine();
        $io->success('Backfill complete.');

        return Command::SUCCESS;
    }
}
